services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - sociopedia-network
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      MONGO_URL: mongodb://db:27017/sociopedia
    networks:
      - sociopedia-network
    depends_on:
      - db

  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - sociopedia-network

networks:
  sociopedia-network:
    driver: bridge

volumes:
  db_data:
    driver: local
